"""
defs/assets/load.py

Terminal load assets — one per source — backed by a shared private helper.

  frost_load_hydrovu  upstream: canonical_bundles_hydrovu
  frost_load_cabq     upstream: canonical_bundles_cabq

All sources share _frost_load() logic. Per-source assets are generated by
_make_frost_load_asset() — adding source 3 is one entry in
shared/source_registry.py's SOURCE_REGISTRY (also used by defs/definitions.py).
commit_watermark is called inside the factory so it can never be forgotten.

No source-specific logic here — the canonical model is the contract.
"""

import logging
from typing import Any

from dagster import AssetExecutionContext, AssetIn, MetadataValue, OpExecutionContext, asset

from aqueduct_dagster.canonical.canonical_model import CanonicalBundle
from aqueduct_dagster.loader.frost_auth import attach_id_token_auth, service_root_url
from aqueduct_dagster.loader.frost_loader import FrostStaClientLoader, observation_records_for
from aqueduct_dagster.loader.watermark_store import FrostWatermarkStore
from aqueduct_dagster.shared.gcs import (
    _gcs_bucket_url,
    _gcs_filesystem,
    commit_watermark,
    transform_watermark_path,
)
from aqueduct_dagster.shared.source_registry import SOURCE_REGISTRY

logger = logging.getLogger(__name__)

FROST_REQUEST_TIMEOUT = 30  # seconds per request; retries handled by _with_retry in frost_loader


def _apply_frost_timeout(service: Any, timeout: int = FROST_REQUEST_TIMEOUT) -> None:
    """Inject a per-request timeout into every SensorThingsService.execute() call."""
    _orig = service.execute

    def _execute_with_timeout(method: str, url: str, **kwargs: Any) -> Any:
        kwargs.setdefault("timeout", timeout)
        return _orig(method, url, **kwargs)

    service.execute = _execute_with_timeout


def build_frost_loader(
    context: AssetExecutionContext | OpExecutionContext, dataset: str
) -> FrostStaClientLoader:
    """
    Builds a FrostStaClientLoader wired to the configured FROST server and a
    dataset-scoped FrostWatermarkStore.

    Shared by every source's frost_load_* asset (via _frost_load, below) and
    by the backfill job (defs/jobs/backfill.py) — both need the exact same
    FROST connection + watermark store construction, so this is written once.

    Which server that is comes from service_root_url(): the local docker FROST by
    default, or a deployed one when FROST_SERVICE_ROOT_URL is set. Because the
    connection is built here, the backfill job authenticates exactly as the assets
    do — there is no second code path to keep in sync.
    """
    import frost_sta_client as fsc

    frost_url = service_root_url()
    service = fsc.SensorThingsService(frost_url)
    # No-op against a local docker FROST; attaches a Cloud Run ID token otherwise.
    attach_id_token_auth(service, frost_url)
    _apply_frost_timeout(service)
    bucket = _gcs_bucket_url().replace("gs://", "")
    watermarks = FrostWatermarkStore(context, _gcs_filesystem(), bucket, dataset=dataset)
    return FrostStaClientLoader(service, watermarks)


def _frost_load(
    context: AssetExecutionContext, bundles: list[CanonicalBundle], *, dataset: str
) -> None:
    """
    Loads a list of CanonicalBundles into FROST via the SensorThings API.
    Called by each source-specific asset — shared logic, no source coupling.

    For each bundle:
      1. ensure_datastream() — idempotent upsert of Thing/Location/Sensor/etc.
      2. load_observations() — filtered by watermark, posted as Data Array chunks
      3. Watermark advanced per chunk — partial failures resume cleanly
    """
    loader = build_frost_loader(context, dataset)

    total_posted = 0
    total_skipped = 0

    for bundle in bundles:
        for datastream in bundle.datastreams:
            ds_id = loader.ensure_datastream(datastream)
            records = observation_records_for(bundle, datastream)
            result = loader.load_observations(datastream.external_key, ds_id, records)
            total_posted += result.posted
            total_skipped += result.skipped

            context.log.info(
                "Datastream %s (FROST id=%s): posted=%d skipped=%d watermark=%s",
                datastream.external_key,
                ds_id,
                result.posted,
                result.skipped,
                result.new_watermark,
            )

    context.log.info(
        "FROST load complete: %d bundle(s), %d posted, %d skipped",
        len(bundles),
        total_posted,
        total_skipped,
    )
    context.add_output_metadata(
        {
            "bundles_loaded": MetadataValue.int(len(bundles)),
            "observations_posted": MetadataValue.int(total_posted),
            "observations_skipped": MetadataValue.int(total_skipped),
        }
    )


def _make_frost_load_asset(name: str, dataset: str) -> Any:
    """
    Generates a frost_load_{name} @asset that:
      1. Calls _frost_load() with the source's FROST watermark dataset.
      2. Calls commit_watermark() after FROST success — always, by construction.

    watermark_path is derived from (dataset, name) via transform_watermark_path(),
    the same function the source's transform.py uses to compute its own WATERMARK_PATH —
    so the read side and write side always agree without either hand-typing the string.

    transform_result must have .bundles: list[CanonicalBundle] and .max_load_id: float | None.
    Both HydroVuTransformResult and CabqTransformResult satisfy this contract.
    """
    watermark_path = transform_watermark_path(dataset, name)

    @asset(
        name=f"frost_load_{name}",
        group_name=name,
        description=f"Loads {name.upper()} CanonicalBundles into the configured FROST server.",
        compute_kind="frost",
        ins={"transform_result": AssetIn(f"canonical_bundles_{name}")},
    )
    def _asset(context: AssetExecutionContext, transform_result: Any) -> None:
        _frost_load(context, transform_result.bundles, dataset=dataset)
        if transform_result.max_load_id is not None:
            commit_watermark(watermark_path, transform_result.max_load_id)
            context.log.info(
                "Transform watermark committed after FROST success: max_load_id=%s",
                transform_result.max_load_id,
            )

    return _asset


# Generate one load asset per source — discovered automatically by load_assets_from_package_module.
# Bound into the module namespace via globals() so adding source 3 to SOURCE_REGISTRY is genuinely
# the only change needed here — no third hardcoded assignment line to remember.
for _cfg in SOURCE_REGISTRY:
    globals()[f"frost_load_{_cfg['name']}"] = _make_frost_load_asset(
        name=_cfg["name"], dataset=_cfg["dataset"]
    )
